name: Update Crypto Cache
on:
  schedule:
    - cron: '2,12,22,32,42,52 * * * *'  # Every 10 minutes at :02, :12, :22, etc
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      LUNARCRUSH_API_KEY: ${{ secrets.LUNARCRUSH_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run cache-update script
        run: node api/cron/update-crypto-data.cjs