name: Update Crypto Cache
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      LUNARCRUSH_API_KEY: ${{ secrets.LUNARCRUSH_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Run cache-update script
        run: node api/cron/update-crypto-data.cjs